{"id": "exceptions-medium-1", "title": "Custom Exception", "description": "Create a custom exception `NegativeNumberError` and raise it when a negative number is passed.", "complexity": "medium", "starter_code": "class NegativeNumberError extends Error {}\n\nfunction checkPositive(num) {\n  if (num < 0) {\n    throw new NegativeNumberError('Negative number error!');\n  }\n}\n\ntry {\n  checkPositive(-5);\n} catch (e) {\n  if (e instanceof NegativeNumberError) {\n    console.log(e.message);\n  }\n}", "visible_test_cases": [{"input": "", "expected_output": "Negative number error!", "output": "Negative number error!"}], "hidden_test_cases": [{"input": "", "expected_output": "Negative number error!", "output": "Negative number error!"}]}